### PR TITLE
Add gvfs dep for file deletion support

### PR DESCRIPTION
**Pull request by vdemin**
See https://discuss.atom.io/t/cant-delete-any-files-on-linux/11216

### CODE REVIEW

**Comment by sjug** [comment]
gvfs would be an optional dependency.

**Comment by vdemin** [comment]
Done.

**Comment by sjug** [comment]
great can you please run, `mksrcinfo` in the directory to update the `.SRCINFO` file

**Comment by vdemin** [comment]
Sorry, I didn't pay attention to this file.

**Comment by sjug** [comment]
No problem, thanks for the pull!

**Pull request merged**
