### PR TITLE
Remove install file

### PR DESCRIPTION
**Pull request by Narrat**
The stuff done in there is covered by a hook provided from desktop-file-utils

### CODE REVIEW

**Comment by sjug** [comment]
Hey @Narrat, can you link me the docs to desktop-file-utils as to how this is now automatic?

**Comment by Narrat** [comment]
https://lists.archlinux.org/pipermail/arch-dev-public/2016-April/027930.html

desktop-file-utils includes the new hook which calls update-desktop-database, whenever a package is installed/updated and places a file into this specific directory ( /usr/share/applications/ )

Commit that added the pacman hook into the package: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/desktop-file-utils&id=f0e4e1b8d15b3b9e0ac1ffb208da7918f041e403

**Comment by sjug** [comment]
Great, thanks. I'll merge this into the next version bump.
Did you want to be included in the contributors list in the PKGBUILD? And if so what email did you want in there?

**Comment by Narrat** [comment]
Not necessary to mention me there ;)

**Pull request merged**
