### PR TITLE
added check for .atom/.npm directory in users home directory to allow…

### PR DESCRIPTION
**Pull request by ghost**
Added check and creation of the ~/.atom/.npm in users home directory.

### CODE REVIEW

**Comment by sjug** [comment]
Hey @rowstu thanks for the pull request.
Are the directories not created if they don't exist already?

**Comment by ghost** [comment]
Not on my fresh install of arch. I had to either manually create them or edit the PKGBUILD to do it for me.

**Comment by Narrat** [comment]
This is regarded as an absolute no-go.
PKGBUILDs and ergo packages don't touch the home directory directly. Never

**Comment by sjug** [comment]
Thanks for the feedback @Narrat, I'll close this PR.

**Pull request closed without merging**
