### PR TITLE
atom-editor: version bump v1.9.0

### PR DESCRIPTION
**Pull request by samueloph**
This new version don't need the package.patch anymore.

### CODE REVIEW

**Comment by juhamust** [comment]
Apparently v1.9.1 is already released: https://github.com/atom/atom/releases/tag/v1.9.1

**Comment by samueloph** [comment]
Thanks @juhamust, i've just updated to 1.9.1.

@sjug Could you please have a look at this?

**Comment by samueloph** [comment]
Just updated to v1.9.2...

**Comment by samueloph** [comment]
Updated to 1.9.3 :)

**Comment by sjug** [comment]
Can you do 1.9.4 please. Thanks!

**Comment by sjug** [comment]
Sorry I've been very busy, do you think we still need that patch?

**Comment by Narrat** [comment]
He removed it, I tested this PR (1.9.3) and Atom still seems to work.
So I guess it really can be removed (Didn't check if the old patch would apply cleanly on 1.9.x. If not this could also be a sign for obsolete changes)

**Comment by samueloph** [comment]
@sjug Sure, I just commited the v1.9.4.

@Narrat is right, the patch is no more needed because it was applied upstream.

Thanks!

**Comment by samueloph** [comment]
v1.9.5 ready to go :)

**Comment by sjug** [comment]
Thanks @samueloph, merged in here, will test the build and push to AUR if it goes well.

**Pull request merged**
